services:
  traefik:
    image: traefik:v3.6
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=hassani.peyman627@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  grabbag-server:
    container_name: grabbag-server
    build:
      context: .
      dockerfile: Dockerfile
    image: grabbag-server:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grabbag.rule=Host(`peymanier.com`)"
      - "traefik.http.routers.grabbag.entrypoints=websecure"
      - "traefik.http.routers.grabbag.tls.certresolver=myresolver"
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - grabbag-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3333/ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - path: .
          action: rebuild

  postgres:
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    container_name: grabbag-postgres
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    networks:
      - grabbag-network
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 3s

volumes:
  pg-data:
  letsencrypt:

networks:
  grabbag-network:
    driver: bridge